### ISSUE TITLE
Python OOP Tutorial 3: classmethods and staticmethods missing code

### ISSUE THREAD

**Issue by marco-vene** [CoreyMSchafer/code_snippets#1]
Hi,
Thanks for the code and youtube tutorial. They are awesome.
I notice that the code of the video is different from the github one.

For instance the class methods are not there.
Would it be possible to share it?

Thanks again,

Marco

**Comment by CoreyMSchafer** [comment]
Sorry for the extremely late reply. The code has now been updated so that it matches the tutorial.
