### ISSUE TITLE
Image is not displayed

### ISSUE THREAD

**Issue by adityakalra581** [CoreyMSchafer/code_snippets#100]
I am not able to display the image in the templates.

```<img` src="images/igl.jpg" alt=""> ```

OUTPUT (In terminal) :
127.0.0.1 - - [11/Apr/2020 19:54:48] "GET /images/igl.jpg HTTP/1.1" 404 -

The image is present in images folder inside the templates folder. I have tried other images with different extensions as well but none worked.
I have tried various things but none of them is displaying the image

![file-structure](https://user-images.githubusercontent.com/51115390/79046597-9991d580-7c2f-11ea-9fd2-92d892f78a77.PNG)

This is the code image. Please if anyone can rectify this issue.

![code](https://user-images.githubusercontent.com/51115390/79046716-305e9200-7c30-11ea-85b6-477327adefdd.PNG)

**Comment by Letlaka** [comment]
Try changing it to this,
<img src="{% static 'images/igl.jpg' %} alt='' ">

**Comment by adityakalra581** [comment]
@Letlaka  Actually i have resolved this issue I'll upload the solution and close the issue soon.
