### ISSUE TITLE
TemplateDoesNotExist at /

### ISSUE THREAD

**Issue by AstroArbaaz** [CoreyMSchafer/code_snippets#109]
Environment:

Request Method: GET
Request URL: https://django-blog-web-app.herokuapp.com/

Django Version: 3.0.4
Python Version: 3.8.2
Installed Applications:
['Blog.apps.BlogConfig',
 'Users.apps.UsersConfig',
 'crispy_forms',
 'django.contrib.admin',
 'django.contrib.auth',
 'django.contrib.contenttypes',
 'django.contrib.sessions',
 'django.contrib.messages',
 'whitenoise.runserver_nostatic',
 'django.contrib.staticfiles']
Installed Middleware:
('whitenoise.middleware.WhiteNoiseMiddleware',
 'django.middleware.security.SecurityMiddleware',
 'whitenoise.middleware.WhiteNoiseMiddleware',
 'django.contrib.sessions.middleware.SessionMiddleware',
 'django.middleware.common.CommonMiddleware',
 'django.middleware.csrf.CsrfViewMiddleware',
 'django.contrib.auth.middleware.AuthenticationMiddleware',
 'django.contrib.messages.middleware.MessageMiddleware',
 'django.middleware.clickjacking.XFrameOptionsMiddleware')

Template loader postmortem
Django tried loading these templates, in this order:

Using engine django:
    * django.template.loaders.app_directories.Loader: /app/Blog/templates/Blog/home.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /app/Users/templates/Blog/home.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /app/.heroku/python/lib/python3.8/site-packages/crispy_forms/templates/Blog/home.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/templates/Blog/home.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /app/.heroku/python/lib/python3.8/site-packages/django/contrib/auth/templates/Blog/home.html (Source does not exist)

Using engine django:
    * django.template.loaders.app_directories.Loader: /app/Blog/templates/Blog/post_list.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /app/Users/templates/Blog/post_list.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /app/.heroku/python/lib/python3.8/site-packages/crispy_forms/templates/Blog/post_list.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /app/.heroku/python/lib/python3.8/site-packages/django/contrib/admin/templates/Blog/post_list.html (Source does not exist)
    * django.template.loaders.app_directories.Loader: /app/.heroku/python/lib/python3.8/site-packages/django/contrib/auth/templates/Blog/post_list.html (Source does not exist)

Traceback (most recent call last):
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 145, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/core/handlers/base.py", line 143, in _get_response
    response = response.render()
  File "/app/.heroku/python/lib/python3.8/site-packages/django/template/response.py", line 105, in render
    self.content = self.rendered_content
  File "/app/.heroku/python/lib/python3.8/site-packages/django/template/response.py", line 81, in rendered_content
    template = self.resolve_template(self.template_name)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/template/response.py", line 63, in resolve_template
    return select_template(template, using=self.using)
  File "/app/.heroku/python/lib/python3.8/site-packages/django/template/loader.py", line 47, in select_template
    raise TemplateDoesNotExist(', '.join(template_name_list), chain=chain)

Exception Type: TemplateDoesNotExist at /
Exception Value: Blog/home.html, Blog/post_list.html

why its throwing me this error, its working fine in localhost not in heroku...
any help?

**Comment by AstroArbaaz** [comment]
it was my mistake

**Comment by amitdcw** [comment]
Hello!
I'm also getting the same error in localhost even. Can you help?
