### ISSUE TITLE
Add a License

### ISSUE THREAD

**Issue by accssharma** [CoreyMSchafer/code_snippets#14]
Add an appropriate license for authorized copy, reproduction of the source code and re-distribution?

**Comment by brylie** [comment]
Yep. License is really important, so that people can re-use this code without individual permission. Simply sharing on GitHub does not make it permissible for people to re-use the code, although the intention to share is nice :-)

**Comment by BakrFrag** [comment]
what do you mean by licence @brylie ???

**Comment by likemoody** [comment]
@BakrFrag https://choosealicense.com/

**Comment by brylie** [comment]
@BakrFrag when we create something, such as code or a photograph, it is automatically protected by international Copyright. This means that only the creator can choose how their creation is used, and grant permissions for others to use the creation through some individual agreement. 

When we share code on GitHub, or elsewhere, it still carries the full Copyright restriction. So, even though we are sharing the code, we have not granted the right for it's re-use. 

Adding a LICENSE.txt to the repository is typically meant to grant universal rights to the shared code, such as the right to re-use or modify the code.

**Comment by CoreyMSchafer** [comment]
I committed a LICENSE.txt to the code_snippets repo. Thanks for pointing that out!

**Comment by accssharma** [comment]
Awesome, thanks for practicing open knowledge sharing and free software practices. You are doing a great job! :)

**Comment by Festusmastermind** [comment]
How will it be known that you reuse the code.....since u are the only one having access to the source code......don't forget that the code can be modify to your taste and new features are added....

Am just curious of what you guys meant by licensing🤔🤔🤔

**Comment by brylie** [comment]
@Festusmastermind by adding an [open source](https://en.wikipedia.org/wiki/Open-source_license) [software license](https://simple.wikipedia.org/wiki/Software_licence) to this repository, @CoreyMSchafer has granted people the right to re-use the software. By default, we don't technically have permission to reuse or build on the software, as it would be protected by the full extent of [Copyright](https://simple.wikipedia.org/wiki/Copyright), which doesn't allow re-use, editing, sharing, etc..
