### ISSUE TITLE
I got a next mistake - save() got an unexpected keyword argument 'force_insert'

### ISSUE THREAD

**Issue by VolodymyrGavrysh** [CoreyMSchafer/code_snippets#15]
obj.save(force_insert=True, using=self.db)
TypeError: save() got an unexpected keyword argument 'force_insert'

After adding additional argument to the class Profile(models.Model): 
(django_project/users/models.py) 
at line 13

**def save(self, **kwargs):**

It starts working

**Comment by tevdevelops** [comment]
Thanks for this update. For me it was:

`def save(self, **kwargs):`

I am sure that was meant though. Thanks again!

**Comment by tomzie27s** [comment]
Thanks!

def save(self, **kwargs):

This one works for me.

**Comment by patrikkiss** [comment]
Great! Had same issue and this worked ! 

Thanks!

**Comment by akshatz** [comment]
Thanks! Had same issue and this worked!

Thanks once again

**Comment by saurabhlabde** [comment]
@Good

**Comment by maruf1847** [comment]
thanks man......i was worried from last night about that....thanks again

**Comment by Lemmy4christ** [comment]
I got this error message, please i need help. 
ValueError at /post/new/
Cannot assign "<SimpleLazyObject: <django.contrib.auth.models.AnonymousUser object at 0x04CF38E0>>": "post.author" must be a "User" instance.


def form_valid(self, form):
		form.instance.author = self.request.user
		return super().form_valid(form)

**Comment by Karanxa** [comment]
thanks

**Comment by Jaspreetkumar1999** [comment]
in user app models.py has save() function change it to
       def save(self, **kwargs):

**Comment by Rahulraifzb** [comment]
Thanks a lot, sir. I try to solve this issue many times.but can't solve this.

**Comment by ChemaJuve** [comment]
So much time searching the error, and finally a short and correct answer. Thanks!
