### ISSUE TITLE
django not sending emails with password reset

### ISSUE THREAD

**Issue by AzharUddinSheikh** [CoreyMSchafer/code_snippets#153]
But whenever I navigate to the http://127.0.0.1:8000 /password-reset/ page and fill in email and click enter the page immediately redirects to
http://127.0.0.1:8000/password-reset/done/ and no email is sent.

no such effort i see in loading this password reset done page , no email i get 
(turn on >> 2nd step verification 
turn on >> low secure app access)

**Comment by BakrFrag** [comment]
first check the following settings in settings.py file 
`
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

EMAIL_HOST = 'smtp.gmail.com'

EMAIL_PORT = 587

EMAIL_USE_TLS = True

EMAIL_HOST_USER = os.environ.get('EMAIL_USER')

EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_PWD')

DEFAULT_FROM_EMAIL = EMAIL_HOST_USER
`
and if you use gmail account don't forget to allow 3rd party application to access 
**you can check this by going to your gmail account settings then security and allow less secure apps to access account**

**Comment by AzharUddinSheikh** [comment]
It's solved
