### ISSUE TITLE
Turn profile update function view to class based view

### ISSUE THREAD

**Issue by ZishuoLi** [CoreyMSchafer/code_snippets#19]
Thanks for bringing such great tutorial, I am really interested in how to change the Profile update function to classed based view.

I did some research, the things covered are mostly based on one form, not combo of two forms, does anyone know how to solve it? thanks

  
    def profile(request):
        if request.method == "POST":

        u_form = UserUpdateForm(request.POST,instance=request.user)
        p_form = ProfileUpdateForm(request.POST,request.FILES,instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request,"Your accunt has been updated, you are now be able to log in !")
            return redirect('profile')
        else:
            u_form = UserUpdateForm(instance=request.user)
            p_form = ProfileUpdateForm(instance=request.user.profile)
        context = {
            'u_form':u_form,
            'p_form':p_form
        }
        return render(request,'users/profile.html',context)

I tried with updateview, detailview, but all fails

thanks

**Comment by AnaAdrian** [comment]
You can use the generic 'View' class, separating the get and post methods.

`from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import View

from .forms import UserUpdateForm, ProfileUpdateForm


class Profile(LoginRequiredMixin, View):
    login_url = 'login'
    redirect_field_name = 'profile'
    
    def get(self, request):
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)
        context = {
            'u_form': u_form,
            'p_form': p_form
        }
        return render(request, 'users/profile.html', context)

    def post(self, request):
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
        
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            messages.success(request, 'Success')
            update_session_auth_has(request, request.user)
            return redirect('profile')`

**Comment by AnaAdrian** [comment]
> You can use the generic View class, separating the get and post methods.
> 
> from django.contrib.auth import update_session_auth_hash
> from django.contrib.auth.mixins import LoginRequiredMixin
> from django.views.generic import View
> 
> from .forms import UserUpdateForm, ProfileUpdateForm
> 
> class Profile(LoginRequiredMixin, View):
> login_url = 'login'
> redirect_field_name = 'profile'
> 
> ```
> def get(self, request):
>     u_form = UserUpdateForm(instance=request.user)
>     p_form = ProfileUpdateForm(instance=request.user.profile)
>     context = {
>         'u_form': u_form,
>         'p_form': p_form
>     }
>     return render(request, 'users/profile.html', context)
> 
> def post(self, request):
>     u_form = UserUpdateForm(request.POST, instance=request.user)
>     p_form = ProfileUpdateForm(request.POST, request.FILES, instance=request.user.profile)
>     
>     if u_form.is_valid() and p_form.is_valid():
>         u_form.save()
>         p_form.save()
>         messages.success(request, 'Success')
>         update_session_auth_has(request, request.user)
>         return redirect('profile')
> ```

**Comment by ZishuoLi** [comment]
Hi AnaAdrian

Thanks, man, it works, especially the update_session_auth_hash part,  really appreciate it!

**Comment by Festusmastermind** [comment]
Nice one.....but I think i still preferred the function based view.....its less code compared with this.....but its good cos you just added to my knowledge
