### ISSUE TITLE
help

### ISSUE THREAD

**Issue by Amanimasila** [CoreyMSchafer/code_snippets#22]
hello my name is Amani , how can you connect flask app with existing database

**Comment by likemoody** [comment]
@Amani, 

Firstly, I am afraid it is not a place to ask such sort of questions. 

Secondy, try finding the answer here: http://flask.pocoo.org/docs/1.0/tutorial/database/

Finally, consider reading the following article please: https://www.pyimagesearch.com/2017/03/06/guide-asking-questions-pyimagesearch-blog/ This will help both YOU and person that will answer the question. 

JM

**Comment by Amanimasila** [comment]
sorry for that, thanks,
