### ISSUE TITLE
TemplateSyntaxError

### ISSUE THREAD

**Issue by ccs1605** [CoreyMSchafer/code_snippets#23]
TemplateSyntaxError at /
Could not parse the remainder: '|' from '|'
error at line 24:
 {% if page_obj.number == num %}﻿

**Comment by likemoody** [comment]
@ccs1605 ,
Have you used {% endif %} to close if statement?
Is num passed as int/float or string.

**Comment by ccs1605** [comment]
thank you for reply.  yes i closed with {% endif %}. i even copied the code but the bug remains.

**Comment by likemoody** [comment]
Provide more of your code please. I don’t see the problem in that chunk of code you pasted here.

**Comment by CoreyMSchafer** [comment]
I'm going to close this. If you still have questions then please send me an email at CoreyMSchafer@gmail.com or leave a comment in the video you're having trouble with.
