### ISSUE TITLE
Invalid syntax

### ISSUE THREAD

**Issue by helenkapatsa** [CoreyMSchafer/code_snippets#26]
Greetings, Corey! Colud you please help a newbie find an answer? Something has changed in BS, so that: 

yt_link = f'https://youtube.com/watch?v={vid_id}'
                                                                                 ^
SyntaxError: invalid syntax

**Comment by khonchafizakaria** [comment]
Video is unavailable.

**Comment by huixinguan** [comment]
I tried your code above, it worked for me. I think it might be the issue with the code related to vid_id.

**Comment by sgowtham1996** [comment]
Can I send me the screen shot so that I could still be clear!

**Comment by sgowtham1996** [comment]
U*

**Comment by sgowtham1996** [comment]
@helenkapatsa try it in a single line,it works completely for me ,if you still get errors try # command use href = True method to get those links

**Comment by chinnutej** [comment]
I'm getting an error
<img width="1591" alt="screenshot 2019-02-17 at 4 07 15 pm" src="https://user-images.githubusercontent.com/46699014/52919249-47c11a00-32ce-11e9-9758-2b45f599c65f.png">

**Comment by borkarfaiz** [comment]
you need to end : at the end of the line

**Comment by CoreyMSchafer** [comment]
@helenkapatsa Did you solve your problem? I'm going to close this issue. I don't check the code snippet issues as frequently as my email, so if you have questions in the future it's probably your best bet to ask there: CoreyMSchafer@gmail.com

Or you can comment on the video in question. Thanks!
