### ISSUE TITLE
log file name doesn't change

### ISSUE THREAD

**Issue by shivrajjadhav733** [CoreyMSchafer/code_snippets#28]
Took codebase from : https://github.com/CoreyMSchafer/code_snippets/tree/master/Decorators
I added below snippet at the end of decorator.py and it should have created log file named as check_kw.log
However, it didn't do it. It just appended the logs created by this function to display_info.log file.
Is there anything else need to change in my_logger?

```
@my_logger
@my_timer
def check_kw(*args, **kwargs):
    time.sleep(1)
    print('check_kw ran with arguments ({}, {})'.format(args, kwargs))


keywordargs = {"arg3": 3, "arg2": "two", "arg1": 5}
check_kw(**keywordargs)

```

**Comment by CoreyMSchafer** [comment]
@shivrajjadhav733 Did you ever figure this out? I don't check GitHub issues as much as email, so in the future if you have questions it's probably best to ask there: CoreyMSchafer@gmail.com

Or comment on the video in question
