### ISSUE TITLE
Flask Mail builtin.OSError Errno 0

### ISSUE THREAD

**Issue by JHero23** [CoreyMSchafer/code_snippets#30]
I wrote the same exact issue, checked my environment settings, printed out everything, and they still give out the same OSError.

**Comment by CoreyMSchafer** [comment]
@JHero23 Did you ever solve this? I don't check GitHub issues as much as I check my email, so in the future it's probably best to ask me questions through there: CoreyMSchafer@gmail.com

Or to comment on the video in question.
