### ISSUE TITLE
Status code 500 via the homepage 127.0.0.1:8000

### ISSUE THREAD

**Issue by nubonics** [CoreyMSchafer/code_snippets#35]
Am attempting to follow along, however I did skip videos 6-11? on the django series. I feel kind of foolish, however I am experiencing this 500 error on the homepage, however, the other pages work as expected. (This is a live version on heroku, but I have my site disabled, as I need to actually add content, and get the homepage to work first :D)

```
Performing system checks...

System check identified no issues (0 silenced).
February 25, 2019 - 23:27:30
Django version 2.1.7, using settings 'django_project.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CTRL-BREAK.
[25/Feb/2019 23:27:33] "GET / HTTP/1.1" 500 27
[25/Feb/2019 23:27:37] "GET /admin/ HTTP/1.1" 302 0
[25/Feb/2019 23:27:37] "GET /admin/login/?next=/admin/ HTTP/1.1" 500 27
[25/Feb/2019 23:27:42] "GET /login HTTP/1.1" 301 0
[25/Feb/2019 23:27:42] "GET /login/ HTTP/1.1" 500 27
[25/Feb/2019 23:27:49] "GET /about/ HTTP/1.1" 500 27
```

Thank you in advance!
Cody Quist

**Comment by CoreyMSchafer** [comment]
It's hard to tell what the error could be if you skipped videos 6-11. We cover a lot of functionality in those videos. I would suggest looking at my code for the last video and comparing it to yours to see what you're missing.

**Comment by nubonics** [comment]
I cloned the repo from your git from the heroku video and followed the steps accordingly. Not sure about the postgresql, however, the rest should be almost identical (server key is not ofc).
