### ISSUE TITLE
Creating super user fails for Django projects

### ISSUE THREAD

**Issue by Chris2L** [CoreyMSchafer/code_snippets#37]
Going through the Django blog project.  I tried a few of the projects and all of the ones I tried (01, 03, 06, 12) and all of them fail when creating a super user from the command line using "python manage.py createsuperuser".  It seems like the only time it works is just as you create the django project.

**Comment by CoreyMSchafer** [comment]
Could you provide more details? What error are you receiving?

**Comment by madjid123** [comment]
Yeah cause when you override save() method you should also pass kwargs and args as parameter. I do it and it's worked `def save(self , *args, **kwargs):
		super(Profile, self).save(*args, **kwargs)
		
		img = Image.open(self.image.path)
		if img.height > 300 or img.width > 300 :
			output_size = ( 300 , 300)
			img.thumbnail(output_size)
			img.save(self.image.path)`

**Comment by madjid123** [comment]
`def save(self , *args, **kwargs):
		super(Profile, self).save(*args, **kwargs)
		
		img = Image.open(self.image.path)
		if img.height > 300 or img.width > 300 :
			output_size = ( 300 , 300)
			img.thumbnail(output_size)
			img.save(self.image.path)`

**Comment by Chris2L** [comment]
Hi Corey

After posting this question I was able to resolve the problem by commenting out the code madjid123 mentioned then it worked.  I'm not sure why it did not work when testing all the other earlier tutorial folders (probably finger trouble).  I have just not had time to look at it again since you asked.

madjid123, I'm sure I tried this and still had issues, but I'll retry when I get time again.

**Comment by jonnyboy101** [comment]
Hi,

I am getting a similar issue, here is my output.  I am using lesson 12 directly from githu, no edits.

I get the error when trying to sign up a new user.  A new user is created in the DB but no profile is created, so I wonder if this is the issue.  

Any help appreciated.

Jon

`

Request Method: | POST
-- | --
http://localhost:8000/register/
2.1
TypeError
save() got an unexpected keyword argument 'force_insert'
C:\Users\admin\AppData\Local\Programs\Python\Python37-32\lib\site-packages\django\db\models\query.py in create, line 413
C:\Users\admin\AppData\Local\Programs\Python\Python37-32\python.exe
3.7.2
['C:\\Users\\git\\code_snippets\\Django_Blog\\12-Password-Reset\\django_project',  'C:\\Users\\Programs\\Python\\Python37-32\\python37.zip',  'C:\\Users\\Programs\\Python\\Python37-32\\DLLs',  'C:\\Users\\Programs\\Python\\Python37-32\\lib',  'C:\\Users\\Programs\\Python\\Python37-32',  'C:\\Users\Roaming\\Python\\Python37\\site-packages',  'C:\\Users\l\\Programs\\Python\\Python37-32\\lib\\site-packages']

`

**Comment by CoreyMSchafer** [comment]
There is an issue with the code in this video that I fixed in the later videos. If you're getting an error that says something like "save() got an unexpected keyword argument 'force_insert'" then please update the save method in users/models.py to the following:
def save(self, *args, **kwargs):
    super().save(*args, **kwargs)﻿

**Comment by jonnyboy101** [comment]
Hi,

Thank you kindly.  I have pushed a change if you wish to accept.  

All the best Jon.
