### ISSUE TITLE
webpage style looks weird after using bootstrap 

### ISSUE THREAD

**Issue by liqi6811** [CoreyMSchafer/code_snippets#64]
Hi Corey, 

Your tutorial is excellent, helped me a lot, thank you so much. 

I followed your steps in tutorial 2 for Flask Blog, when I used bootstrap the webpage styling did not change, all the navigation bars are stuck together. I am not sure why? 

By the way I am using python 2, does bootstrap require python 3? 

Thank you, 
Ling

**Comment by imkaka** [comment]
As in tutorials if you are using CDN, it should work fine, try these if you are stuck.
- Try to update the CDN with the latest one from [Bootstrap Official](https://getbootstrap.com/docs/4.3/getting-started/introduction/#starter-template) and have those properly.
- It requires Internet, It won't work if you are offline.
- Use Bootstrap classes properly.
- Bootstrap is independent of Python version you use.

**Comment by liqi6811** [comment]
thank you so much, it is working now :)

**Comment by imkaka** [comment]
@liqi6811 you can close this issue. :v:

**Comment by liqi6811** [comment]
resolve, thank you @imkaka
