### ISSUE TITLE
TypeError - save() got an unexpected keyword argument 'force_insert' 

### ISSUE THREAD

**Issue by soumyaa1804** [CoreyMSchafer/code_snippets#77]
I encountered this error in the 12th tutorial when I tried to register a new user on the app.
I found the solution here: https://stackoverflow.com/questions/52351756/django-typeerror-save-got-an-unexpected-keyword-argument-force-insert/52351829
It worked for me. :)

**Comment by zafercuz** [comment]
Corey actually pinned a solution on the comment section on part 9 of the tutorial.

**Comment by soumyaa1804** [comment]
Yes, he mentioned it in further video. I got to know about it later as I moved forward with the tutorial series. Thanks anyway. :)

**Comment by zafercuz** [comment]
I also found out about it when I was at part 11, was really frustrating to have that error. Had to rewind a couple of videos then found out Corey's comment lmao.
