### ISSUE TITLE
self.email = firt + "." + last + "@company.com"

### ISSUE THREAD

**Issue by alsafiameer** [CoreyMSchafer/code_snippets#9]
https://github.com/CoreyMSchafer/code_snippets/blob/3e23f3ecc7f6ff0a8a1b55df297673d0618e9137/Object-Oriented/6-property-decorator/oop.py#L7

Corey, 
thanks for your imazing playlist at youtube, but this is something i did not quite understood ! why var update (first) did not pass to the email! 
it does passed to full name function! but it does not to email!!

**Comment by CoreyMSchafer** [comment]
Hey there. That's because the full name method gets that value every time it is run, but when we set the email it only got set in the __init__ method once. So the property decorator we use in this tutorial fixes that.
