### ISSUE TITLE
TypeError: as_view() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by dronov-dmitry** [CoreyMSchafer/code_snippets#90]
http://i.imgur.com/5Isj67L.png

**Comment by dronov-dmitry** [comment]
sorry its my mistake

**Comment by sanix-sandel** [comment]
I need a flask celery factory pattern, I tried by all means but i'm just
receiving an RunTime Errorr, it's said that I need to add app_context().
Please need your help

Le jeu. 23 janv. 2020 à 23:16, dronov-dmitry <notifications@github.com> a
écrit :
